### ISSUE TITLE
ERROR: Failed to run childProcess

### ISSUE THREAD

**Issue by spaceo** [matis-dk/ts-compile-checker#1]
For some reason when I run the action in Github it fails with the message:
```
Error: ERROR: Failed to run childProcess
(node:1606) UnhandledPromiseRejectionWarning: Error: TypeError: Cannot read property 'toString' of null
    at /home/runner/.npm/_npx/1606/lib/node_modules/ts-compile-checker/dist/index.js:222:27
    at step (/home/runner/.npm/_npx/1606/lib/node_modules/ts-compile-checker/dist/index.js:34:23)
    at Object.next (/home/runner/.npm/_npx/1606/lib/node_modules/ts-compile-checker/dist/index.js:15:53)
    at fulfilled (/home/runner/.npm/_npx/1606/lib/node_modules/ts-compile-checker/dist/index.js:6:58)
(node:1606) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1606) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

* It does not fail when I run `npx ts-compile-checker` locally.
* Node version is: v12.22.0 both local and in GH actions

Job looks like:
```
  typescript:
    name: Typescript compile check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - name: Run typecript compile check
        run: npx ts-compile-checker
        working-directory: ./
```
